// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE

import * as List from "bs-platform/lib/es6/list.js";
import * as Styles from "./styles.bs.js";
import * as Tea_html from "bucklescript-tea/src-ocaml/tea_html.js";

function view(dialog) {
  var view_choice = function (param) {
    return Tea_html.button(undefined, undefined, /* :: */[
                Tea_html.onClick(param[1]),
                /* [] */0
              ], /* :: */[
                Tea_html.text(param[0]),
                /* [] */0
              ]);
  };
  return Tea_html.div(undefined, undefined, /* :: */[
              Tea_html.class$prime(Styles.dialog_class),
              /* [] */0
            ], /* :: */[
              Tea_html.h3(undefined, undefined, /* [] */0, /* :: */[
                    Tea_html.text(dialog[/* title */0]),
                    /* [] */0
                  ]),
              /* :: */[
                Tea_html.p(undefined, undefined, /* [] */0, /* :: */[
                      Tea_html.text(dialog[/* message */1]),
                      /* [] */0
                    ]),
                /* :: */[
                  Tea_html.div(undefined, undefined, /* [] */0, List.map(view_choice, dialog[/* choices */2])),
                  /* [] */0
                ]
              ]
            ]);
}

export {
  view ,
  
}
/* Styles Not a pure module */
