// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE

import * as Block from "bs-platform/lib/es6/block.js";
import * as Curry from "bs-platform/lib/es6/curry.js";
import * as Styles from "./styles.bs.js";
import * as Tea_cmd from "bucklescript-tea/src-ocaml/tea_cmd.js";
import * as Tea_sub from "bucklescript-tea/src-ocaml/tea_sub.js";
import * as Tea_navigation from "bucklescript-tea/src-ocaml/tea_navigation.js";
import * as DecisionMatrixEditing from "./decisionMatrixEditing.bs.js";
import * as DecisionMatrixEditingView from "./decisionMatrixEditingView.bs.js";

var program = Tea_navigation.navigationProgram((function ($$location) {
        return /* LocationChanged */Block.__(9, [$$location]);
      }), /* record */[
      /* init */DecisionMatrixEditing.init,
      /* update */DecisionMatrixEditing.update,
      /* view */DecisionMatrixEditingView.view,
      /* subscriptions */(function (param) {
          return Tea_sub.none;
        }),
      /* shutdown */(function (param) {
          return Tea_cmd.none;
        })
    ]);

function main(web_node, unit) {
  var style = document.createElement("style");
  document.head.appendChild(style);
  style.innerHTML = Styles.style;
  return Curry._2(program, web_node, unit);
}

export {
  main ,
  
}
/* program Not a pure module */
